/**
 * OpenAI providers. Cineforge's text/Director work runs on Anthropic (Claude);
 * OpenAI covers the two jobs it's best at in this pipeline:
 *   • Images — GPT-image-1 for seed frames (drives image-to-video) + stills.
 *   • Voice  — TTS (tts-1, voice "onyx") for narration / dialogue.
 *
 * Both implement a small adapter contract and stay behind the same boundary as
 * the video models: a key in env, an optional storage `upload` hook, no callers
 * coupled to OpenAI. No Node types required (uses DOM `atob`/`fetch`).
 */

export interface ImageGenRequest {
  prompt: string;
  width?: number;
  height?: number;
}
export interface ImageGenResult {
  imageKey: string; // storage key if uploaded, else a data: URL
  width: number;
  height: number;
}
export interface ImageModelAdapter {
  readonly id: string;
  generate(req: ImageGenRequest, signal?: AbortSignal): Promise<ImageGenResult>;
}

export interface TtsRequest {
  text: string;
  voice?: string;
}
export interface TtsResult {
  audioKey: string;
}
export interface TtsAdapter {
  readonly id: string;
  synthesize(req: TtsRequest, signal?: AbortSignal): Promise<TtsResult>;
}

/** Persist generated bytes to our storage and return the key. */
export type UploadBytes = (bytes: Uint8Array, contentType: string) => Promise<string>;

interface CommonOpts {
  apiKey: string;
  upload?: UploadBytes;
  fetchImpl?: typeof fetch;
}

function decodeBase64(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/** Map a target resolution to GPT-image-1's three supported orientations. */
function pickSize(w?: number, h?: number): { size: string; width: number; height: number } {
  if (w && h && w > h) return { size: "1536x1024", width: 1536, height: 1024 };
  if (w && h && h > w) return { size: "1024x1536", width: 1024, height: 1536 };
  return { size: "1024x1024", width: 1024, height: 1024 };
}

/* ── Images — GPT-image-1 ────────────────────────────────────── */
export interface OpenAIImageOptions extends CommonOpts {
  model?: string; // default gpt-image-1
}
export class OpenAIImageAdapter implements ImageModelAdapter {
  readonly id = "openai-image";
  private readonly fetch: typeof fetch;
  constructor(private readonly opts: OpenAIImageOptions) {
    this.fetch = opts.fetchImpl ?? fetch;
  }
  async generate(req: ImageGenRequest, signal?: AbortSignal): Promise<ImageGenResult> {
    const { size, width, height } = pickSize(req.width, req.height);
    const res = await this.fetch("https://api.openai.com/v1/images/generations", {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${this.opts.apiKey}` },
      body: JSON.stringify({ model: this.opts.model ?? "gpt-image-1", prompt: req.prompt, size, n: 1 }),
      signal,
    });
    if (!res.ok) throw new Error(`OpenAI images ${res.status}: ${await res.text()}`);
    const json = (await res.json()) as { data?: { b64_json?: string; url?: string }[] };
    const first = json.data?.[0];
    if (!first?.b64_json && !first?.url) throw new Error("OpenAI images: empty response");

    if (first.b64_json) {
      const bytes = decodeBase64(first.b64_json);
      const imageKey = this.opts.upload ? await this.opts.upload(bytes, "image/png") : `data:image/png;base64,${first.b64_json}`;
      return { imageKey, width, height };
    }
    return { imageKey: first.url!, width, height };
  }
}

/* ── Voice — TTS (tts-1, onyx) ───────────────────────────────── */
export interface OpenAITtsOptions extends CommonOpts {
  model?: string; // default tts-1
  voice?: string; // default onyx
}
export class OpenAITtsAdapter implements TtsAdapter {
  readonly id = "openai-tts";
  private readonly fetch: typeof fetch;
  constructor(private readonly opts: OpenAITtsOptions) {
    this.fetch = opts.fetchImpl ?? fetch;
  }
  async synthesize(req: TtsRequest, signal?: AbortSignal): Promise<TtsResult> {
    if (!this.opts.upload) throw new Error("OpenAITtsAdapter requires an upload hook for the audio bytes");
    const res = await this.fetch("https://api.openai.com/v1/audio/speech", {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${this.opts.apiKey}` },
      body: JSON.stringify({
        model: this.opts.model ?? "tts-1",
        voice: req.voice ?? this.opts.voice ?? "onyx",
        input: req.text.slice(0, 4000),
        response_format: "mp3",
      }),
      signal,
    });
    if (!res.ok) throw new Error(`OpenAI TTS ${res.status}: ${await res.text()}`);
    const bytes = new Uint8Array(await res.arrayBuffer());
    const audioKey = await this.opts.upload(bytes, "audio/mpeg");
    return { audioKey };
  }
}

/** Build OpenAI providers from env (returns what's configured). */
export interface OpenAIEnv {
  OPENAI_API_KEY?: string;
  OPENAI_IMAGE_MODEL?: string;
  OPENAI_TTS_MODEL?: string;
  OPENAI_TTS_VOICE?: string;
}
export function buildOpenAIProviders(
  env: OpenAIEnv,
  upload?: UploadBytes,
): { image?: OpenAIImageAdapter; tts?: OpenAITtsAdapter } {
  if (!env.OPENAI_API_KEY) return {};
  return {
    image: new OpenAIImageAdapter({ apiKey: env.OPENAI_API_KEY, model: env.OPENAI_IMAGE_MODEL, upload }),
    tts: new OpenAITtsAdapter({ apiKey: env.OPENAI_API_KEY, model: env.OPENAI_TTS_MODEL, voice: env.OPENAI_TTS_VOICE, upload }),
  };
}
