/**
 * Sound design in the worker (DirectorOS W16; Part 1 §18): a scene's ambience
 * bed and its planned effects, generated by a text-to-audio model and stored
 * content-addressed — the same request (model, prompt, length) is generated
 * once and reused, so a place that sounds the same in two scenes gets the very
 * same bed (consistent room tone) and is never paid for twice.
 */
import { createHash } from "node:crypto";
import type { SceneSoundPlan } from "@cineforge/movie";
import { SCORE_MODEL } from "./score";

export const SOUND_MODEL = () => process.env.FAL_SOUND_MODEL ?? SCORE_MODEL;
export const SOUND_PREFIX = "audio_cache/sound";

export interface SoundDeps {
  model: string;
  /** Generate audio for a prompt (metered by the caller's implementation). */
  generate(prompt: string, seconds: number): Promise<{ bytes: Uint8Array; contentType: string }>;
  exists(key: string): Promise<boolean>;
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
}

export interface SoundAsset {
  key: string;
  cached: boolean;
  prompt: string;
  seconds: number;
}

export function soundKey(model: string, prompt: string, seconds: number): string {
  const h = createHash("sha256").update(JSON.stringify({ v: 1, model, prompt: prompt.trim(), seconds })).digest("hex");
  return `${SOUND_PREFIX}/${h}`;
}

export async function renderSound(prompt: string, seconds: number, deps: SoundDeps): Promise<SoundAsset> {
  const key = soundKey(deps.model, prompt, seconds);
  if (await deps.exists(key)) return { key, cached: true, prompt, seconds };
  const { bytes, contentType } = await deps.generate(prompt, seconds);
  if (!bytes.length) throw new Error("the sound model returned no audio");
  await deps.put(key, bytes, contentType);
  return { key, cached: false, prompt, seconds };
}

export interface SoundTrackRow {
  kind: "AMBIENCE" | "SFX";
  key: string;
  startMs: number;
  durationMs: number;
  meta: Record<string, unknown>;
}

/** The ambience bed: under the whole scene, from its start. */
export function ambienceRow(plan: SceneSoundPlan, a: SoundAsset, model: string): SoundTrackRow {
  return {
    kind: "AMBIENCE", key: a.key, startMs: 0, durationMs: Math.round(plan.plannedSec * 1000),
    meta: { provider: "fal", model, prompt: a.prompt, seconds: a.seconds, cached: a.cached, plannedSceneMs: Math.round(plan.plannedSec * 1000), loop: true },
  };
}

/** One effect at its planned moment (the render rescales it to the scene as cut). */
export function sfxRow(plan: SceneSoundPlan, cue: SceneSoundPlan["sfx"][number], a: SoundAsset, model: string): SoundTrackRow {
  return {
    kind: "SFX", key: a.key, startMs: Math.round(cue.atSec * 1000), durationMs: Math.round(cue.seconds * 1000),
    meta: { provider: "fal", model, cue: cue.cue, prompt: a.prompt, anchor: cue.anchor, shotIndex: cue.shotIndex, cached: a.cached, plannedSceneMs: Math.round(plan.plannedSec * 1000) },
  };
}
