/**
 * Video worker — consumes `video-queue`, generates one shot via the model
 * abstraction layer (Wan 2.1 / Hunyuan on RunPod A40), runs QC, stores the
 * result, and meters cost. See docs/09, docs/13, docs/24 §C7/§C8.
 *
 * Phase 3 additions:
 *  - Content-addressed cache (C7): before spending GPU, reuse an existing READY
 *    clip in the same project with the same cacheKey (editor re-render / repeats).
 *  - Cost metering + credit debit (C8): only billed when GPU is actually used.
 */
import { Worker, UnrecoverableError } from "bullmq";
import { QUEUES, shouldPauseForBudget, type VideoJob } from "@cineforge/shared";
import { buildClusterRegistry, buildOpenAIProviders, MODEL_VERSIONS, type ShotRequest } from "@cineforge/model-adapters";
import { prisma } from "@cineforge/db";
import { realtime } from "../realtime";
import { S3Storage } from "../storage/storage";

// Bytes uploader for provider adapters (OpenAI seed frames).
const storage = new S3Storage();

const connection = { url: process.env.REDIS_URL ?? "redis://localhost:6379" };

// Multi-GPU dispatch (docs/24 §C5): each model is backed by N workers
// (WAN_GPU_URLS / HUNYUAN_GPU_URLS comma-separated), round-robined per call.
// An external provider (text/image-to-video) is registered automatically when
// EXTERNAL_VIDEO_API_URL is set — drop a key in, no code changes (docs/22).
const assetBase = process.env.ASSET_PUBLIC_BASE_URL?.replace(/\/$/, "");
const registry = buildClusterRegistry(
  {
    WAN_GPU_URLS: process.env.WAN_GPU_URLS,
    WAN_GPU_URL: process.env.WAN_GPU_URL,
    HUNYUAN_GPU_URLS: process.env.HUNYUAN_GPU_URLS,
    HUNYUAN_GPU_URL: process.env.HUNYUAN_GPU_URL,
    RUNPOD_API_KEY: process.env.RUNPOD_API_KEY,
    EXTERNAL_VIDEO_API_URL: process.env.EXTERNAL_VIDEO_API_URL,
    EXTERNAL_VIDEO_API_KEY: process.env.EXTERNAL_VIDEO_API_KEY,
    EXTERNAL_VIDEO_MODEL_ID: process.env.EXTERNAL_VIDEO_MODEL_ID,
    EXTERNAL_VIDEO_MODEL_NAME: process.env.EXTERNAL_VIDEO_MODEL_NAME,
    EXTERNAL_VIDEO_MAX_SEC: process.env.EXTERNAL_VIDEO_MAX_SEC,
  },
  {
    // External providers fetch the seed frame / reference video by URL; resolve
    // our (private) storage key to a public/CDN URL. Self-hosted workers read
    // keys directly, so this only matters for the external adapter. Swap in a
    // signed-URL resolver here if the bucket isn't fronted by a public CDN.
    resolveImageUrl: assetBase ? async (key: string) => `${assetBase}/${key}` : undefined,
    resolveVideoUrl: assetBase ? async (key: string) => `${assetBase}/${key}` : undefined,
  },
);

type ShotWithScene = Awaited<ReturnType<typeof loadShot>>;

function loadShot(shotId: string) {
  return prisma.shot.findUniqueOrThrow({
    where: { id: shotId },
    include: { scene: { include: { project: true, location: true } } },
  });
}

/** Compose the final ShotRequest. `seedKey` is the resolved seed frame for
 *  image-to-video (uploaded by the creator, or generated by OpenAI). */
function buildShotRequest(shot: ShotWithScene, seedKey?: string): ShotRequest {
  const [w, h] = shot.scene.project.aspectRatio === "9:16" ? [720, 1280] : [1280, 720];
  // video-to-video: an uploaded reference video drives the motion style.
  const refVideo = shot.referenceVideoKey && !PREVIEW_SEED.test(shot.referenceVideoKey) ? shot.referenceVideoKey : undefined;
  return {
    prompt: shot.prompt,
    negativePrompt: shot.negativePrompt ?? undefined,
    seed: shot.seed ? Number(shot.seed) : undefined,
    durationSec: shot.durationSec,
    width: w,
    height: h,
    camera: (shot.cameraPlan as unknown as ShotRequest["camera"]) ?? undefined,
    referenceImageKeys: seedKey ? [seedKey] : undefined,
    referenceVideoKeys: refVideo ? [refVideo] : undefined,
    videoOp: refVideo ? "style" : undefined,
    motionStrength: refVideo ? 0.7 : undefined,
  };
}

// Web-only markers from the preview UI — not real storage keys.
const PREVIEW_SEED = /^(generated:|local:|ref:)/;

/**
 * Resolve the seed frame for an image-to-video shot:
 *  1. a creator-UPLOADED seed (a real storage key) is used as-is;
 *  2. otherwise, if OpenAI is configured, GENERATE one (GPT-image-1) from the
 *     shot prompt, upload it, and persist the key;
 *  3. otherwise fall back to text-to-video (no seed).
 */
async function resolveSeedKey(shot: ShotWithScene): Promise<string | undefined> {
  if (shot.source !== "image") return undefined;
  if (shot.seedImageKey && !PREVIEW_SEED.test(shot.seedImageKey)) return shot.seedImageKey; // uploaded
  if (!process.env.OPENAI_API_KEY || !process.env.S3_BUCKET) return undefined;

  const key = `projects/${shot.scene.projectId}/seeds/${shot.id}.png`;
  const { image } = buildOpenAIProviders(process.env, (bytes, ct) => storage.putBytes(key, bytes, ct));
  if (!image) return undefined;
  const [w, h] = shot.scene.project.aspectRatio === "9:16" ? [720, 1280] : [1280, 720];
  const { imageKey } = await image.generate({ prompt: shot.prompt, width: w, height: h });
  await prisma.shot.update({ where: { id: shot.id }, data: { seedImageKey: imageKey } });
  return imageKey;
}

/** Look for an already-generated clip with the same cacheKey in this project. */
async function findCacheHit(shot: ShotWithScene): Promise<{ videoKey: string; thumbnailKey: string | null } | null> {
  if (!shot.cacheKey) return null;
  const hit = await prisma.shot.findFirst({
    where: {
      cacheKey: shot.cacheKey,
      status: "READY",
      videoKey: { not: null },
      id: { not: shot.id },
      scene: { projectId: shot.scene.projectId },
    },
    select: { videoKey: true, thumbnailKey: true },
    orderBy: { updatedAt: "desc" },
  });
  return hit?.videoKey ? { videoKey: hit.videoKey, thumbnailKey: hit.thumbnailKey } : null;
}

export const videoWorker = new Worker<VideoJob>(
  QUEUES.video,
  async (job) => {
    const { shotId, modelId, projectId, sceneId } = job.data;
    const shot = await loadShot(shotId);

    // ── Idempotent resume (C8): a shot already generated is a no-op ──────
    if (shot.status === "READY" && shot.videoKey) {
      await realtime.emit("shot.ready", { projectId, sceneId, shotId, thumbnailKey: shot.thumbnailKey ?? undefined });
      return { shotId, videoKey: shot.videoKey, gpuMs: 0, alreadyDone: true };
    }

    // ── Budget pause gate (C8): stop dispatching GPU work when paused ────
    if (shot.scene.project.status === "PAUSED") {
      throw new UnrecoverableError("project paused (budget ceiling reached)");
    }

    // ── Cache hit (C7): reuse an identical clip, zero GPU spend ──────────
    const cached = await findCacheHit(shot);
    if (cached) {
      await prisma.shot.update({
        where: { id: shotId },
        data: {
          status: "READY",
          videoKey: cached.videoKey,
          thumbnailKey: cached.thumbnailKey,
          gpuMs: 0,
          attempts: { increment: 1 },
        },
      });
      await realtime.emit("shot.ready", { projectId, sceneId, shotId, thumbnailKey: cached.thumbnailKey ?? undefined });
      return { shotId, videoKey: cached.videoKey, gpuMs: 0, cached: true };
    }

    // ── Generate ────────────────────────────────────────────────────────
    const adapter = registry.get(modelId);
    await prisma.shot.update({ where: { id: shotId }, data: { status: "GENERATING" } });

    // image-to-video: use the uploaded seed, or generate one (OpenAI) first.
    const seedKey = await resolveSeedKey(shot);
    const result = await adapter.generate(buildShotRequest(shot, seedKey));

    // QC gate (docs/09) omitted here; on failure throw to trigger retry.

    await prisma.shot.update({
      where: { id: shotId },
      data: {
        status: "READY",
        videoKey: result.videoKey,
        thumbnailKey: result.thumbnailKey,
        seed: BigInt(result.seed),
        gpuMs: result.gpuMs,
        modelVersion: shot.modelVersion ?? MODEL_VERSIONS[modelId],
        attempts: { increment: 1 },
      },
    });

    // ── Meter + debit + budget tracking (C8) ────────────────────────────
    const { userId } = shot.scene.project;
    const [, , updatedProject] = await prisma.$transaction([
      prisma.usageRecord.create({
        data: { userId, projectId, gpuMs: result.gpuMs, kind: "video" },
      }),
      prisma.user.update({
        where: { id: userId },
        data: { creditsMs: { decrement: result.gpuMs } },
      }),
      prisma.project.update({
        where: { id: projectId },
        data: { spentMs: { increment: result.gpuMs } },
        select: { spentMs: true, estimatedMs: true },
      }),
    ]);

    await realtime.emit("shot.ready", { projectId, sceneId, shotId, thumbnailKey: result.thumbnailKey });

    // Pause the project if it blew past its budget ceiling. Already-queued
    // shots then fail-fast at the gate above; the GPU drains and shuts down.
    if (shouldPauseForBudget(updatedProject.estimatedMs, updatedProject.spentMs)) {
      await prisma.project.update({
        where: { id: projectId },
        data: { status: "PAUSED", errorMessage: "Budget ceiling reached" },
      });
      await realtime.emit("project.paused", {
        projectId,
        reason: "budget",
        spentMs: updatedProject.spentMs,
        estimatedMs: updatedProject.estimatedMs ?? undefined,
      });
    }

    return { shotId, videoKey: result.videoKey, gpuMs: result.gpuMs };
  },
  {
    connection,
    concurrency: Number(process.env.VIDEO_CONCURRENCY ?? 4), // bounded by GPU pool
    limiter: { max: 100, duration: 1000 },
  },
);
